version: '3.1'
services:
  proxy:
    image: nginx:1.21.4
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./resources/the-celeb:/home/ubuntu/resources/the-celeb
    ports:
     - '80:80'
    #  - '8080:80'
    command: [nginx-debug, '-g', 'daemon off;']